list.files()
dataset <-read.csv("stroopdata.csv")
hist(dataset$Congruent,col="red", xlab="Congruent Samples", main="Congruent Data Set Histogram")
hist(dataset$Incongruent,col="blue", xlab="Incongruent Samples", main="Incongruent Data Set Histogram")
boxplot(dataset$Congruent, main="dataset$Congruent")
boxplot(dataset$Incongruent, main="dataset$Incongruent")
xc <- c(dataset$Congruent)
xic <- c(dataset$Incongruent)
mus <-(xc-xic)
boxplot(mus, main="Derived Data Set", xlab="Difference of Sample Data", ylab="Frequency")
boxplot(mus,main="Derived Data Set Boxplot")
plot(mus, main="Derived Data Set")
h<-hist(mus, breaks=10, col="red", xlab="Sample Calculated Difference", 
        main="Derived Data Set Histogram") 
xfit<-seq(min(mus),max(mus),length=40) 
yfit<-dnorm(xfit,mean=mean(mus),sd=sd(mus)) 
yfit <- yfit*diff(h$mids[1:2])*length(mus) 
lines(xfit, yfit, col="blue", lwd=2)
plot(density(mus))
hist(mus)
print(xc)
print(xic)
print(mus)
M1 = mean(mus)
print(M1)
S1 = sd(mus)
print(S1)
print(t.test(xc,xic,alternative = "two.sided", mu = 0, paired =TRUE, var.equal = FALSE, conf.level = 0.95))
print(t.test(xc,xic,alternative = "less", mu = 0, paired =TRUE, var.equal = FALSE, conf.level = 0.95))


